batch_size: [8, 16, 32, 64]
# intermediate_layer_idx: ["0 6 11"]
intermediate_layer_idx: [
                        "0 1 5", "0 1 8", "0 1 11", "1 5 11", "0 4 11", "0 1 2 5", "0 1 2 8", "0 1 2 11", # 3 layers
                        "0 1 5 8 11", "0 1 7 9 11", "0 1 6 9 11", "0 2 6 8 11", # 5 layers
                        "0 1 3 5 8 11", "0 1 3 7 8 11", "0 1 4 5 9 11", "0 1 3 6 9 11", "0 2 3 5 8 11", # 6 layers
                        "0 1 2 3 4 8 11", "0 1 2 3 5 8 11", "0 1 2 3 7 9 11", "0 1 2 3 6 9 11", "0 1 2 5 8 11", # 7 layers
                    ]

model:  [
            'dinov2_vitb14',
            # 'dinov2_vits14',
            # 'dinov2_vitl14',
            # 'deit_tiny_patch16_224',
            # 'deit_small_patch16_224',
            # 'deit_base_patch16_224',  
            # 'deit_base_patch16_384',
            # 'efficientnet_b0',
            # 'efficientnet_b1',
            # 'efficientnet_b2',
            # 'efficientnet_b3',
            # 'resnet18',
            # 'resnet34',
            # 'resnet50',
            # 'resnet101',
        ]

opt: ["adam", "momentum", "sgd", "adamw"]
opt_betas: 
    options: ["0.9 0.999", "0 0.99", "0.9 0.99", "0 0.999"]
    only_active_with: {"opt": ["adam", "adamw"]}

momentum: 
    options: [0.0, 0.8, 0.9, 0.95, 0.99]
    only_active_with: {"opt": ["momentum"]}

weight_decay: [0.1, 0.01, 0.001, 0.0001, 0.00001, 0.0]

sched: ["step", "multistep", "plateau", "cosine", "None"]

lr: [0.01, 0.001, 0.0001, 0.00005]
epochs: [50]

step_size: 
    options: [10, 20, 30]
    only_active_with: {"sched": ["step"]}
milestones:
    options: ["10 20 30", "5 10 15 20 25 30", "5 10 15 20 25 30 35 40 45"]
    only_active_with: {"sched": ["multistep"]}
patience_epochs: 
    options: [2, 5, 10]
    only_active_with: {"sched": ["plateau"]}
factor: 
    options: [0.1, 0.5, 0.75]
    only_active_with: {"sched": ["plateau"]}
mode: 
    options: ["min", "max"]
    only_active_with: {"sched": ["plateau"]}
T_max: 
    options: [10, 20, 50]
    only_active_with: {"sched": ["cosine"]}
eta_min:
    options: [0.0, 0.0001, 0.001]
    only_active_with: {"sched": ["cosine"]}


# data_augmentation: [None, "trivial_augment", "random_augment", "auto_augment"]
# auto_augment: 
#     options: [None, "v0", "original"]
#     only_active_with: {"data_augmentation": ["auto_augment"]}
# ra_num_ops: 
#     options: [2, 3]
#     only_active_with: {"data_augmentation": ["random_augment"]}
# ra_magnitude:
#     options: [9, 17]
#     only_active_with: {"data_augmentation": ["random_augment"]}
