defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: default  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

best_trial_path: "SkinCancerDataset-20240806-204503/0"

dataset_name: "SkinCancerDataset" # FashionDataset, FlowersDataset, EmotionsDataset, SkinCancerDataset
